env: dev # 环境，线上环境：prod、测试环境：dev
baseUrl: http://127.0.0.1:8088 # 网站域名
port: 8088 # 端口
logFile: ./logs/cde.log # 日志文件
staticPath: /data/www  # 根路径下的静态文件目录，可配置绝对路径

## 数据库连接
database:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  pass: raspberrypi
  dbname: cde_db
  charset: utf8mb4
  loc: Asia/Shanghai
